#cloud-config
bootcmd:
  - 'ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf'
  - 'systemctl mask swap.target'
  - 'swapoff -a'
  #- 'mkfs.ext4 /dev/vdb'
apt:
  primary:
    - arches: [default]
      uri: $ubuntu_mirror
salt_minion:
  conf:
    master: $salt_master
  grains:
    app: elasticsearch
    datacenter: $datacenter
    elasticsearch:
      role: $elastic_role
mounts:
  - [ swap ]
  #- [ /dev/vdb, /data_elasticsearch1 ]
swap:
  size: 0
runcmd:
  - salt-call grains.items
  - $salt_cmd
