#cloud-config
bootcmd:
  - 'ln -sf /run/systemd/resolve/resolv.conf /etc/resolv.conf'
  - 'systemctl mask swap.target'
  - 'swapoff -a'
apt:
  primary:
    - arches: [default]
      uri: http://catboat.discdrive.bayphoto.com/ubuntu/
salt_minion:
  conf:
    master: $salt_master
  grains:
    app: elasticsearch
    datacenter: $datacenter
    elasticsearch:
      role: $elastic_role
mounts:
  - [ swap ]
swap:
  size: 0
runcmd:
  - salt-call grains.items
  - $salt_cmd
